language: ruby
rvm:
- 1.9.3
- 2.0.0
deploy:
  provider: rubygems
  api_key:
    secure: tZYTVOUWGEXpTVz4yjsGrMj4+QQ8DHbCbW+O0wKe+ohXttxG7T6xFOhuqAFjgvfEWRc93+/XVSQTXNNFbXO1NV1jNnSwHNoFe6aAZi825D6WeoeqiJHtsGGEoA8AH34B7sfCi20d5FOwrHkHTf9iG9KxZNdmUPHOEIbqaSA9shhtOqV2xp2a2IO24XmUBVT83slqm8w8zlJ0RziF+neSQJ/Tz+Ce4Z7QwaD0XV3sBS1kC4labwGUuWcfTxlpwNf1qs3IqcZIKg+WpTJG8JHGuV4CGpE6rb6VeqAz68L+Jx704f+jDJneKr8GzzFOmCZxUVg+bBMcbM1bjQXKDcCSdepKTNV2JGkzZF3ziAhhAAZfEAtZBPeGc4S5pNsW6gLboGPM3NiofekrcPwMw4HAghf9I3qbokvJd0nxQPzMyriKW0AamZEkw62lxA3ccB9yUJlIYEJqvn40J1T+y6KRD6Td/QRuVKS3N3I6zd+GnO4kjwOAkc6QGWEhLQWNUZ8R0ZZw9h8BfJVR2n6JJb4b4KflTIAooP53VURaQnLqVD2nKlNoTEuieOW2uiKrgvy8Pf+X+pf9GaxSY0N4jgYXrjeLXO2U4qfHXGa0OaZnKtxFK2OzX15g8TaRwuFcKGrfbgWHL5kTFF2qqPUaPsLQhR8LUDferXs7xeqTKR9p+rw=
  gem: consul-migrate
  on:
    tags: true
    repo: Cimpress-MCP/consul-migrate
